### ISSUE TITLE
get-reads-alt-unmap.sh problem

### ISSUE THREAD

**Issue by SusieX** [humanlongevity/HLA#12]
Because my bamfile were generated from HISAT2, I tried to convert them first using get-reads-alt-unmap.sh
./get-reads-alt-unmap.sh inbam outbam

Then there are a lot of warnings and finally an error message:
...
*****WARNING: Query K00153:41:H3MLCBBXX:7:2228:8450:33123 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
[E::bwa_idx_load_from_disk] fail to locate the index files

How do I deal with this? My input bam file is already sorted and indexed.
Thanks

**Comment by SusieX** [comment]
Also when I run this:
sudo docker run -v `pwd`:`pwd` -w `pwd` humanlongevity/hla \
    --sample_id test \
    --input_bam_path input.bam \
    --output_path test

I got permission denied:
typer.sh parameters: DELETE=false FULL=false
mkdir: cannot create directory 'hla-test': Permission denied
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', '/mnt/BigData1/Susie/PlatesRNA.HISAT2.RF/bam1_4/P1_10169_9.RF.sorted_n.bam', 'test']' returned non-zero exit status 1


Should I change anything in the commend? 

Many thanks,

**Comment by tanghaibao** [comment]
@SusieX 
Were you able to process the test BAM as stated in the README without an error?
I have not run HISAT2 before and would need a test BAM to diagnose the problem. Is there a smaller file that you can share?

Haibao

**Comment by SusieX** [comment]
Hi,
I copy/pasted the test code into my terminal and this is what I got:
/HLA/xHLA$ sudo docker run -v `pwd`:`pwd` -w `pwd` humanlongevity/hla     --sample_id test --input_bam_path tests/test.bam     --output_path test

[30/Oct/2017 13:54:47] INFO - Xie Chao's HLA typing algorithm
[30/Oct/2017 13:54:47] INFO - Sample_id: test Input file: tests/test.bam
typer.sh parameters: DELETE=false FULL=false
mkdir: cannot create directory 'hla-test': Permission denied
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'tests/test.bam', 'test']' returned non-zero exit status 1

Is it because docker tried to create folder 'hla-test' in github directory? Or should I change path in the commend (I'm not familiar with docker)? 
If I download the scripts in bin/ and files in data/, will I be able to run xHLA in my local ubuntu terminal ?

Thanks,

**Comment by melnel000** [comment]
My bam file was generated using BWA-mem aligning to hg38 with alt contigs. I have tried to preprocess my bam files using the script get-reads-alt-unmap.sh so that I can run xHLA. However, I receive the following error:

Merging sorted chunks...
[==============================================================================]
[bwt_restore_sa] SA-BWT inconsistency: primary is not the same. Abort!
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "-".
sambamba-sort: not enough data in stream

What could the problem be?

Thanks

**Comment by tkerby** [comment]
I'm getting the same issue with an HG38 aligned bam file from Dante. I think its the same issue as seen here: https://github.com/FredHutch/SEACR/issues/26
