### ISSUE TITLE
Massive memory issue

### ISSUE THREAD

**Issue by bcal94** [humanlongevity/HLA#13]
Occasionally even after running BAMS through get-reads-alt-unmap.sh XHla still uses upwards of 500gb of ram.  Is there any further recommendations for pre processing?

**Comment by tanghaibao** [comment]
@bcal94 
Did the memory issue occur during `get-reads-alt-unmap.sh` or during the HLA step?

**Comment by bcal94** [comment]
during the HLA step

**Comment by tanghaibao** [comment]
I have not yet seen this before - if you can pin down at which sub-step during HLA this occurs, it might help me diagnose. And please feel free to send me the screen output.

**Comment by bcal94** [comment]
27/Dec/2017 19:34:46] INFO - Xie Chao's HLA typing algorithm
[27/Dec/2017 19:34:46] INFO - Sample_id: sliced_TCGA-BH-A0HL-01A-11W-A050-09_IlluminaGA-DNASeq_exome_gdc_realn.bam.filtered.bam Input file: sliced_TCGA-BH-A0HL-01A-11W-A050-09_IlluminaGA-DNASeq_exome_gdc_realn.bam.filtered.bam
typer.sh parameters: DELETE=false FULL=false
Extracting reads from S3
Aligning reads to IMGT database
processing FASTQ file
	found 7560 reads
processing MSA file
	found 26381 HLA exons
processing FASTQ file
	matched to 21689 HLA exons
	356 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
[1] 169323
[1] 169323
[1] 1949
[1] 249
[1] 132078
[1] 98658
[1] 73502
[1] 25156
dcast
done dcast
weight
done weight
set to 1
done set to 1
dcast2
done dcast2
lpsolve
done lpsolve
 [1] "A*02:01"    "A*30:01"    "B*15:50"    "B*38:01"    "C*07:01"   
 [6] "DPB1*02:01" "DQB1*06:02" "DQB1*06:03" "DRB1*13:01" "DRB1*14:01"
pulling non-core exons in
  DRB1*14:01 
"DRB1*14:54" 
  B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01 
"B*57:01" "B*57:02" "B*57:03" "B*57:05" "B*57:11" "B*13:04" "B*57:29" "B*57:04" 
  B*18:01   B*18:01 
"B*57:48" "B*57:71" 
  B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01   B*18:01 
"B*57:01" "B*57:02" "B*57:03" "B*57:05" "B*57:11" "B*13:04" "B*57:29" "B*57:04" 
  B*18:01   B*18:01 
"B*57:48" "B*57:71" 
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 4 of list input is not a data.frame, data.table or list
Calls: do.call -> <Anonymous> -> rbind -> <Anonymous> -> rbindlist
In addition: Warning message:
In mclapply(solution, function(s) { :
  scheduled cores 4 encountered errors in user code, all values of the jobs will be affected
Execution halted
Warning message:
system call failed: Cannot allocate memory 
Traceback (most recent call last):
  File "/apps/xhla/10.04.2017/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/apps/python/2.7.11/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/apps/xhla/10.04.2017/bin/typer.sh', 'sliced_TCGA-BH-A0HL-01A-11W-A050-09_IlluminaGA-DNASeq_exome_gdc_realn.bam.filtered.bam', 'sliced_TCGA-BH-A0HL-01A-11W-A050-09_IlluminaGA-DNASeq_exome_gdc_realn.bam.filtered.bam']' returned non-zero exit status 1
77.49user 7.26system 2:09.88elapsed 65%CPU (0avgtext+0avgdata 311016maxresident)k
10544inputs+0outputs (64major+559183minor)pagefaults 0swaps



Im running with 500gb of ram with partial bam containing only chromosome 6 and have already been filtered with your provided script.

**Comment by tanghaibao** [comment]
@bcal94 
Thanks for sending this along - I'll take a look when I get back to work this week.

Haibao
