### ISSUE TITLE
error occured when running

### ISSUE THREAD

**Issue by zd200572** [humanlongevity/HLA#14]
done lpsolve
 [1] "A*24:02"    "A*33:03"    "B*15:01"    "B*58:01"    "C*03:02"   
 [6] "C*04:01"    "DPB1*02:01" "DPB1*04:01" "DQB1*02:01" "DQB1*05:03"
[11] "DRB1*03:01" "DRB1*14:05"
pulling non-core exons in
Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: do.call -> mclapply -> lapply -> FUN -> mcfork
Execution halted
Warning message:
system call failed: Cannot allocate memory 
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'hla-1-no-filter.sam.bam.sorted.bam', 'test']' returned non-zero exit status 1
################################################
the bam file size is only 170 Mb, I used a cloud server (8cores+24G ram), I don't know why this error happens. Can anyone help me!

**Comment by zd200572** [comment]
what's more! I used a pcr sequencing result.

**Comment by tanghaibao** [comment]
@zd200572 
The error message suggested that there's not enough memory for this run. I understand the starting bam size is only 170Mb but the R script we currently used consumes quite a bit of memory.
