### ISSUE TITLE
is this a bug or something wrong with my test data?

### ISSUE THREAD

**Issue by zd200572** [humanlongevity/HLA#17]
I use this software according to the article, and I got this error:
Extracting reads from S3
skipped 98412 duplicated reads
Aligning reads to IMGT database
processing FASTQ file
	found 151748 reads
processing MSA file
	found 26381 HLA exons
processing FASTQ file
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
	matched to 0 HLA exons
	0 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
Error in fread(align.path) : File is empty: hla-1c/1c.tsv
Execution halted
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'HLA-1-clean_sorted.bam', '1c']' returned non-zero exit status 1

**Comment by zd200572** [comment]
I baidu the error innfo and know it is the out range of my ram.
