### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by compbio** [humanlongevity/HLA#22]
It would be great if you can take a look at what happened and give me some clue!
Thanks!

2018-01-11T18:02:17.464782174Z processing FASTQ file
2018-01-11T18:02:17.474653029Z 	found 2796 reads
2018-01-11T18:02:17.474664030Z processing MSA file
2018-01-11T18:02:17.897350913Z 	found 26381 HLA exons
2018-01-11T18:02:17.897375302Z processing FASTQ file
2018-01-11T18:02:26.875431019Z 	matched to 9790 HLA exons
2018-01-11T18:02:26.875466077Z 	262 reads matched to HLA types not in the MSA file
2018-01-11T18:02:26.944128389Z translating matches to MSA
2018-01-11T18:02:28.212725340Z Error in apply(mat2[, solution], 1, max) : 
2018-01-11T18:02:28.212744859Z   dim(X) must have a positive length
2018-01-11T18:02:28.212755739Z Execution halted
2018-01-11T18:02:28.221492161Z Traceback (most recent call last):
2018-01-11T18:02:28.221508050Z   File "/opt/bin/run.py", line 64, in <module>
2018-01-11T18:02:28.221514672Z     check_call(bin_args)
2018-01-11T18:02:28.221517873Z   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
2018-01-11T18:02:28.221525322Z     raise CalledProcessError(retcode, cmd)
2018-01-11T18:02:28.221536499Z subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', '/sbgenomics/Projects/11c7a09c-16a8-4ea2-a781-01709f9943c7/NA12878-Garvan-Vial1_R.bam', 'NA12878-Garvan-Vial1', 'delete', 'full']' returned non-zero exit status 1

**Comment by teolmste** [comment]
I am having the same error message. For some of my files, it appears to give a single HLA type, but then reads dim(X) must have a positive length.... as per above.
