### ISSUE TITLE
samtools view: failed to open

### ISSUE THREAD

**Issue by bwubb** [humanlongevity/HLA#23]
Greetings,

  I have not seen my particular issue posted yet, and hopefully it is not too trivial (but I suspect it is). I am able to run the test.bam no problem. When I try some of my data, samtools says it does not exist. And I assure you the file exists and can be viewed outside of this deployment.

```
docker run -v `pwd:`pwd` -w `pwd` humanlongevity/hla --sample_id "120002" --input_bam_path "/home/bwubb/Parvati/bam_data/FLG2_AFR/GRCh38/120002.ready.bam" --output_path test
[19/Jan/2018 18:55:25] INFO - Xie Chao's HLA typing algorithm
[19/Jan/2018 18:55:25] INFO - Sample_id: 120002 Input file: /home/bwubb/Parvati/bam_data/FLG2_AFR/GRCh38/120002.ready.bam
typer.sh parameters: DELETE=false FULL=false
Extracting reads from S3
[E::hts_open_format] fail to open file '/home/bwubb/Parvati/bam_data/FLG2_AFR/GRCh38/120002.ready.bam'
samtools view: failed to open "/home/bwubb/Parvati/bam_data/FLG2_AFR/GRCh38/120002.ready.bam" for reading: No such file or directory
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', '/home/bwubb/Parvati/bam_data/FLG2_AFR/GRCh38/120002.ready.bam', '120002']' returned non-zero exit status 1
```
Hopefully, I am just overlooking something foolish. Thank you.

**Comment by bwubb** [comment]
Ooof. A misunderstanding of how docker operates. Was not mounting volumes that had a direct path to bam.
