### ISSUE TITLE
Why xHLA does not work for test.bam

### ISSUE THREAD

**Issue by dulunar** [humanlongevity/HLA#49]
I used xHLA in WSL, but I found that I cann't test it, as follow:

docker pull humanlongevity/hla
Using default tag: latest
latest: Pulling from humanlongevity/hla
ab26a7a684ab: Pull complete
f39ad1e4649c: Pull complete
d8b3c1aee01f: Pull complete
2c6ea9f43a60: Pull complete
1cc53c212be4: Pull complete
5f54d3b9b0fa: Pull complete
ff22e3ae8553: Pull complete
55cdfec7d780: Pull complete
607aa3828258: Pull complete
e542261b255c: Pull complete
fa0348e95780: Pull complete
422e3508e617: Pull complete
f49897c45a91: Pull complete
ba9e2f3cc2c4: Pull complete
007700dc3f3f: Pull complete
270f7cdfe1aa: Pull complete
a98c82717073: Pull complete
f12abe75f70a: Pull complete
Digest: sha256:425487b5203485506d30254f03d438aee7d0322938b76bd4a7d3ac201a1ac0e9
Status: Downloaded newer image for humanlongevity/hla:latest

docker run -v `pwd`:`pwd` -w `pwd` humanlongevity/hla --sample_id test --input_bam_path tests/test.bam --output_path test
[06/Nov/2019 16:51:26] INFO - Xie Chao's HLA typing algorithm
[06/Nov/2019 16:51:26] INFO - Sample_id: test Input file: tests/test.bam
typer.sh parameters: DELETE=false FULL=false
Extracting reads from S3
[E::hts_open_format] fail to open file 'tests/test.bam'
samtools view: failed to open "tests/test.bam" for reading: No such file or directory
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'tests/test.bam', 'test']' returned non-zero exit status 1

docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by tao-bioinfo** [comment]
You should download `tests/test.bam` from this github directory and put it in your current folder
