### ISSUE TITLE
error in more$solution $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by alexvpickering** [humanlongevity/HLA#55]
here is the full output:

```bash
[12/Jun/2020 16:16:54] INFO - Xie Chao's HLA typing algorithm
[12/Jun/2020 16:16:54] INFO - Sample_id: 09KTG_TGACCA Input file: ./results/mapped_reads/09KTG_TGACCA.bam
typer.sh parameters: DELETE=false FULL=false
Extracting reads from S3
Aligning reads to IMGT database
processing FASTQ file
        found 916 reads
processing MSA file
        found 26381 HLA exons
processing FASTQ file
        matched to 9482 HLA exons
        203 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
[1] 13918
[1] 13918
[1] 142
[1] 55
[1] 10218
[1] 5065
[1] 1568
[1] 3497
dcast
done dcast
weight
done weight
set to 1
done set to 1
dcast2
done dcast2
lpsolve
done lpsolve
[1] "DPB1*04:01" "DQB1*06:02"
pulling non-core exons in
Warning message:
In mclapply(solution, function(s) { :
  all scheduled cores encountered errors in user code
Error in more$solution : $ operator is invalid for atomic vectors
Calls: unique
Execution halted
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', './results/mapped_reads/09KTG_TGACCA.bam', '09KTG_TGACCA']' returned non-zero exit status 1
```

**Comment by nyoonhee** [comment]
I'm having the same issue for one of my WES sample. All other samples in my cohort ran well. Any updates?
