### ISSUE TITLE
Unable to compile xHLA

### ISSUE THREAD

**Issue by dhwnai2410** [humanlongevity/HLA#6]
dhwani@dhwani-Precision-WorkStation-T7500:~/Documents/hla_scan/test_out/HLA-master/docker$ make build
docker build -t docker-dev.hli.io/xchao/hla-dev -f dev.dockerfile .
flag provided but not defined: -f

Usage: docker build [OPTIONS] PATH | URL | -

Build a new container image from the source code at PATH

  -q=false: Suppress verbose build output
  -t="": Tag to be applied to the resulting image in case of success
docker tag docker-dev.hli.io/xchao/hla-dev docker-dev.hli.io/xchao/hla-dev:0.0.0
2017/07/17 10:35:27 dial unix /var/run/docker.sock: permission denied
make: *** [build] Error 1

**Comment by tanghaibao** [comment]
@dhwnai2410 it may be that your docker version is too low. What's the output of `docker -v`? It might be worthwhile to upgrade to the [latest version](https://www.docker.com/community-edition).

**Comment by dhwnai2410** [comment]
version  .0.5.3

**Comment by tanghaibao** [comment]
@dhwnai2410 this is an outdated version. Would you mind trying to upgrade docker to a more recent version?

**Comment by dhwnai2410** [comment]
anurag@anurag-Precision-WorkStation-T5400:~/Downloads/HLA-master/docker$ sudo make build
[sudo] password for anurag: 
Sorry, try again.
[sudo] password for anurag: 
docker build -t docker-dev.hli.io/xchao/hla-dev -f dev.dockerfile .
Sending build context to Docker daemon 17.92 kB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu

cb56c90f0b30: Pull complete 
0acc551e5716: Pull complete 
8956dcd35143: Pull complete 
908242721214: Pull complete 
b44ff14dd3bb: Pull complete 
Digest: sha256:5faf6cb681da2be979a177b60d8c18497f962e3d82268c49db6c74008d0c294d
Status: Downloaded newer image for ubuntu:14.04
 ---> 4a2820e686c4
Step 2 : RUN sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list' 	&& gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 	&& gpg -a --export E084DAB9 | sudo apt-key add -
 ---> Running in b30541f46944
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key E084DAB9 from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list' 	&& gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 	&& gpg -a --export E084DAB9 | sudo apt-key add -' returned a non-zero code: 2
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by dhwnai2410** [comment]
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017

**Comment by tanghaibao** [comment]
Not sure why the compile failed. It works for me and other users. I have pushed a compiled image `tanghaibao/hla`. Would you test it out?

```bash
docker pull tanghaibao/hla
docker run -v `pwd`:`pwd` -w `pwd` tanghaibao/hla \
    --sample_id test --input_bam_path test.bam \
    --output_path test
```

**Comment by dhwnai2410** [comment]
where 'pwd' is written do I need to put the present working directory. 

i tried using this command

docker run -v `pwd`:`pwd` -w `pwd` tanghaibao/hla --sample_id test --/home/dhwani/Desktop/sequences/hg38 abc_sorted_hg38.bam --output_path test

it shows error flag provided but not defined: -w

**Comment by dhwnai2410** [comment]
anurag@anurag-Precision-WorkStation-T5400:~/Desktop/dhwani$ sudo docker run -v `pwd`:`pwd` -w `pwd` tanghaibao/hla --sample_id test --input_bam_path abc_hg38.bam --output_path test
[23/Jul/2017 03:49:40] INFO - Xie Chao's HLA typing algorithm
[23/Jul/2017 03:49:40] INFO - Sample_id: test Input file: abc_hg38.bam
Extracting reads from S3
skipped 7306 duplicated reads
Aligning reads to IMGT database
processing FASTQ file
	found 35475 reads
processing MSA file
	found 26381 HLA exons
processing FASTQ file
Error: Invalid input file format
	matched to 0 HLA exons
	0 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
Error in fread(align.path) : File is empty: hla-test/test.tsv
Execution halted
Traceback (most recent call last):
  File "/opt/bin/run.py", line 57, in <module>
    check_call([bin_path, args.input_bam_path, args.sample_id])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'abc_hg38.bam', 'test']' returned non-zero exit status 1
